--- 

- name: Install dependens
  become: true
  apt:
    name:
      - wget
      - gnupg
      - apt-transport-https
      - lsb-release
    state: present
    update_cache: yes

- name: Download Zabbix release
  get_url:
    url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu24.04_all.deb"
    dest: /tmp/zabbix-release.deb

- name: Install Zabbix release 
  become: true
  apt:
    deb: /tmp/zabbix-release.deb
    update_cache: yes

- name: Install Zabbix and dependens (PostgreSQL Nginx)
  apt:
    name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - zabbix-sql-scripts
      - zabbix-nginx-conf
      - zabbix-agent
      - postgresql
      - php-fpm
      - nginx 
      - php-cli 
      - php-mbstring 
      - php-gd 
      - php-xml 
      - php-bcmath 
      - php-ldap 
      - php-pgsql 
      - php-zip 
      - php-json 
      - php-curl 
      - php-xmlrpc 
      - php-bcmath
    state: present
    update_cache: yes

- name: Copy zabbix access configuration
  become: true
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/16/main/pg_hba.conf
    group: postgres
    mode: '0640'
    owner: postgres

- name: Copy zabbix php configuration
  become: true
  template:
    src: php.ini
    dest: /etc/php/8.3/fpm/php.ini
    mode: '0644'

- name: Copy zabbix nginx configuration
  become: true
  template:
    src: zabbix
    dest: /etc/nginx/sites-available/zabbix
    mode: '0644'

- name: Simlimks sites-enabled
  file:
    src: /etc/nginx/sites-available/zabbix
    dest: /etc/nginx/sites-enabled/zabbix
    state: link
    force: yes

- name: Remove default nginx site configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove default nginx site configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Check configurate nginx
  become: true
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0

- name: PostgreSQL restarted
  service:
    name: postgresql
    state: restarted
    enabled: true

- name: Create PostgreSQL user zabbix_user
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: zabbix_user
    password: passwd
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
    login_unix_socket: /var/run/postgresql
    state: present

- name: Create my_wiki owner wikiuser
  become: true
  community.postgresql.postgresql_db:
    name: zabbix
    owner: zabbix_user
    state: present
  become_user: postgres

- name: Import scheme for Zabbix
  become_user: postgres
  shell: |
    zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | PGPASSWORD='passwd' psql -U zabbix_user -d zabbix

- name: Mark scheme
  file:
    path: /var/lib/postgresql/.zabbix_schema_loaded
    state: touch

- name: Copy file zabbix_server for zabbix
  become: true
  copy:
    src: zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
    owner: sys_admin
    group: sys_admin
    mode: '0644'

- name: Copy file zabbix_server.conf.php
  become: true
  copy:
    src: zabbix.conf.php
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: www-data
    group: www-data
    mode: '0600'

- name: Включить службы
  service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - zabbix-server
    - zabbix-agent
    - php8.3-fpm
    - nginx
