---
- name: Download zabbix-release
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu24.04_all.deb
    dest: /tmp/zabbix-release_6.4-1+ubuntu24.04_all.deb

- name: Install zabbix-release
  ansible.builtin.apt:
    deb: /tmp/zabbix-release_6.4-1+ubuntu24.04_all.deb
    update_cache: yes

- name: Update cache apt
  ansible.builtin.apt:
    update_cache: yes

- name: Install zabbix_agent
  become: true
  apt:
    name: zabbix-agent
    state: present

- name: Configuring zabbix-agent
  ansible.builtin.template:
    src: zabbix_agentd.j2
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Restarting and enabling zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Restarting and enabling nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

