---
- name: Add GPG-key PostgreSQL
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add repository PostgreSQL (PGDG) для Ubuntu 22.04
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main"
    filename: "pgdg"
    state: present

- name: Update_cache
  apt:
    update_cache: yes      

- name: Install PostgresSQL
  apt:
    name: "postgresql-16"
    state: present

- name: Copy database configuration primary
  template:
    src: full_postgresql.conf.j2
    dest: /etc/postgresql/16/main/postgresql.conf
    group: postgres
    mode: '0644'
    owner: postgres

- name: Copy user access configuration
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/16/main/pg_hba.conf
    group: postgres
    mode: '0640'
    owner: postgres

