# tasks for postgresql_claster
---
- name: Установка repmgr
  become: true
  apt:
    name: 
      - repmgr
      - postgresql-16-repmgr
    state: present

- name: Проверить наличие repmgr_funcs.so
  stat:
    path: "/usr/lib/postgresql/16/lib/repmgr_funcs.so"
  register: repmgr_funcs

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    enabled: yes
    state: restarted


- name: Setup repmgr user and database
  become: true
  become_user: postgres
  ignore_errors: yes
  shell: |
    createuser --replication --createdb --createrole --superuser repmgr &&
    psql -c 'ALTER USER repmgr SET search_path TO repmgr_test, "$user", public;' &&
    createdb repmgr --owner=repmgr
  when: "'bd_primary' in inventory_hostname or 'bd_standby' in inventory_hostname"

- name: Copy repmgr configuration in primary
  template:
    src: repmgr_primary.conf.j2
    dest: /etc/repmgr.conf
  when: "'bd_primary' in inventory_hostname"

- name: Copy repmgr configuration in primary
  template:
    src: repmgr_standby.conf.j2
    dest: /etc/repmgr.conf
  when: "'bd_standby' in inventory_hostname"


- name: Restart PostgreSQL
  systemd:
    name: postgresql
    enabled: yes
    state: restarted
  when: "'bd_primary' in inventory_hostname or 'bd_standby' in inventory_hostname"

- name: Register primary node
  become_user: postgres
  shell: repmgr primary register
  ignore_errors: yes
  when: "'bd_primary' in inventory_hostname"
 
- name: Stop PostgreSQL
  systemd:
    name: postgresql
    state: stopped
  when: "'bd_standby' in inventory_hostname"
 
- name: Clean up PostgreSQL data directory
  become_user: postgres
  file:
    path: /var/lib/postgresql/16/main
    force: yes
    state: absent
  when: "'bd_standby' in inventory_hostname"
 
- name: Clone primary node data
  become_user: postgres
  shell: repmgr -h 192.168.10.10 -U repmgr -d repmgr -f /etc/repmgr.conf standby clone
  ignore_errors: yes
  when: "'bd_standby' in inventory_hostname"
 
- name: Start PostgreSQL
  systemd:
    name: postgresql
    state: started
  when: "'bd_standby' in inventory_hostname"
 
- name: Register standby node
  become_user: postgres
  shell: repmgr standby register
  ignore_errors: yes
  when: "'bd_standby' in inventory_hostname"

- name: Add postgres in google-sudoers for pg_ctlcluster
  user:
    name: postgres
    groups: google-sudoers
    append: yes

- name: Ensure repmgrd service is started and enabled
  become: true
  ansible.builtin.systemd:
    name: repmgrd
    enabled: yes
    state: started
