---
- name: Download zabbix-release
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu24.04_all.deb
    dest: /tmp/zabbix-release_6.4-1+ubuntu24.04_all.deb

- name: Install zabbix-release
  ansible.builtin.apt:
    deb: /tmp/zabbix-release_6.4-1+ubuntu24.04_all.deb

- name: Update cache apt
  ansible.builtin.apt:
    update_cache: yes

- name: Install dependencies
  become: true
  apt:
    name:
      - build-essential
      - python3-pip
      - python3-dev
      - libpq-dev
      - python3-psycopg2
      - zabbix-agent
    state: present
    update_cache: yes

- name: Configuring zabbix-agent
  ansible.builtin.template:
    src: zabbix_agentd.j2
    dest: /etc/zabbix/zabbix_agentd.conf

#- name: Restarting and enabling zabbix-agent
#  ansible.builtin.service:
#    name: zabbix-agent
#    state: restarted
#    enabled: yes 
