---
- name: Install Python client dependencies
  become: true
  apt:
    name:
      - build-essential
      - python3-pip
      - python3-dev
      - libpq-dev
      - python3-psycopg2
    state: present
    update_cache: yes

