- name: Install OpenSSH
  apt:
    name: openssh-server
    update_cache: yes
    state: present
 
- name: Create postgres SSH directory
  file:
    mode: '0755'
    owner: postgres
    group: postgres
    path: /var/lib/postgresql/.ssh/
    state: directory
  when: "'bd_primary' in inventory_hostname or 'bd_standby' in inventory_hostname"
 
- name: Copy SSH private key for repmgr
  copy:
    src: id_rsa
    dest: /var/lib/postgresql/.ssh/id_rsa
    owner: postgres
    group: postgres
    mode: '0600'
  when: "'bd_primary' in inventory_hostname or 'bd_standby' in inventory_hostname"
 
- name: Copy SSH public key for repmgr
  copy:
    src: id_rsa.pub
    dest: /var/lib/postgresql/.ssh/id_rsa.pub
    owner: postgres
    group: postgres
    mode: '0644'
  when: "'bd_primary' in inventory_hostname or 'bd_standby' in inventory_hostname"
 
- name: Add key to authorized keys file
  authorized_key:
    user: postgres
    state: present
    key: "{{ lookup('file', 'keys/id_rsa.pub') }}"
  when: "'bd_primary' in inventory_hostname or 'bd_standby' in inventory_hostname"
 
- name: Restart SSH service
  service:
    name: sshd
    enabled: yes
    state: restarted---
