- name: Install OpenSSH
  apt:
    name: openssh-server
    update_cache: yes
    state: present
 
- name: Create postgres SSH directory
  file:
    mode: '0755'
    owner: postgres
    group: postgres
    path: /var/lib/postgresql/.ssh/
    state: directory
 
- name: Copy SSH private key for repmgr
  copy:
    src: "keys/id_rsa"
    dest: /var/lib/postgresql/.ssh/id_rsa
    owner: postgres
    group: postgres
    mode: '0600'
 
- name: Copy SSH public key for repmgr
  copy:
    src: "keys/id_rsa.pub"
    dest: /var/lib/postgresql/.ssh/id_rsa.pub
    owner: postgres
    group: postgres
    mode: '0644'
 
- name: Add key to authorized keys file
  authorized_key:
    user: postgres
    state: present
    key: "{{ lookup('file', 'keys/id_rsa.pub') }}"

- name: Change PasswordAuthentication in sshd_config
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Add StrictHostKeyChecking in SSH
  become: true
  lineinfile:
    path: /etc/ssh/ssh_config
    state: present
    regexp: '^StrictHostKeyChecking'
    line: 'StrictHostKeyChecking accept-new'
 
- name: Restart SSH service
  service:
    name: sshd
    enabled: yes
    state: restarted
