linux: #Группа хостов
  children: #Обозначение, что будет подгруппа хостов
    postgres_cluster: #Имя подгруппы хостов
      hosts: #Узлы группы
        bd_primary:
          ansible_host: 89.169.156.226
        bd_standby:
          ansible_host: 51.250.78.132
    media_wiki:
      hosts:    
        wiki_1:
          ansible_host: 89.169.131.185
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: admin
    ansible_ssh_private_key_file: ~/Sys_admin_12/ssh_cloud/id_ed25519
    ansible_become: true #Становиться ли другим пользователем после подключения
    #become_user: root
