linux: #Группа хостов
  children: #Обозначение, что будет подгруппа хостов
    postgres_cluster: #Имя подгруппы хостов
      hosts: #Узлы группы
        bd_primary:
          ansible_host:
        bd_standby:
          ansible_host:
    backup_con:
      hosts:
        backup_console:
          ansible_host:
    media_wiki:
      hosts:    
        wiki_1:
          ansible_host:
        wiki_2:
          ansible_host:
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: sys_admin
    ansible_ssh_private_key_file: ~/Sys_admin_12/ssh_cloud/id_ed25519
    ansible_become: true #Становиться ли другим пользователем после подключения
    #become_user: root
