linux: #Группа хостов
  children: #Обозначение, что будет подгруппа хостов
    postgres_cluster: #Имя подгруппы хостов
      hosts: #Узлы группы
        bd_primary:
          ansible_host:
        bd_standby:
          ansible_host:
    trash:
      hosts:    
        vm_3:
          ansible_host:
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: admin
    ansible_ssh_private_key_file: ~/Sys_admin_12/ssh_cloud/id_ed25519
    ansible_become: true #Становиться ли другим пользователем после подключения
    #become_user: root
