linux: #Группа хостов
  children: #Обозначение, что будет подгруппа хостов
    postgres_cluster: #Имя подгруппы хостов
      hosts: #Узлы группы
        bd_primary:
          ansible_host: 158.160.49.12
        bd_standby:
          ansible_host: 158.160.43.231
    backup_con:
      hosts:    
        backup_console:
          ansible_host: 51.250.6.103
    media_wiki:
      hosts:    
        wiki_1:
          ansible_host: 158.160.62.171
        wiki_2:
          ansible_host: 158.160.62.233
    load_balancer:
      hosts:
        balancer:
          ansible_host: 46.21.245.173
    zabbix_server:
      hosts:
        zabbix:
          ansible_host: 62.84.118.199
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: sys_admin
    ansible_ssh_private_key_file: ~/Sys_admin_12/ssh_cloud/id_ed25519
    ansible_become: true #Становиться ли другим пользователем после подключения
    #become_user: root
