--- 
#- name: Установка стандартных пакетов
#  hosts: all
#  roles:
#    - role: default_packages
#  tags:
#    - install_packages

#- name: Установка и настройка nginx c кастомной страницей
#  hosts: nginx # Будет работать на узлах в группе nginx
#  roles:
#    - role: nginx_custom
#  tags:
#    - nginx_custom 
- name: Установка default_package
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: default_package
  tags:
    - default_package

- name: Установка postgresql
  hosts: postgres_cluster:media_wiki:backup_con
  become: yes
  roles:
    - role: install_postgres
  tags:
    - install_postgres

- name: Установка ssh
  hosts: postgres_cluster:media_wiki:backup_con
  become: yes
  roles:
    - role: install_ssh
  tags:
    - install_ssh

- name: Установка repmgr
  hosts: postgres_cluster
  become: yes
  roles:
    - role: install_repmgr
  tags:
    - install_repmgr

- name: Создать пользователя wikiuser и базу данных
  hosts: postgres_cluster
  become: yes
  roles:
    - role: create_wiki_db
  tags:
    - create_wiki_db

- name: Настройка бэкапа
  hosts: postgres_cluster:backup_con
  become: yes
  roles:
    - role: backup
  tags:
    - backup

- name: Запускаем Media_wiki
  hosts: media_wiki
  become: yes
  roles:
    - role: install_wiki
  tags:
    - install_wiki

- name: Запускаем балансировщик
  hosts: balancer
  become: yes
  roles:
    - role: load_balancer
  tags:
    - load_balancer

- name: Запускаем zabbix
  hosts: zabbix
  become: yes
  roles:
    - role: zabbix_server
  tags:
    - zabbix_server

