--- 
#- name: Установка стандартных пакетов
#  hosts: all
#  roles:
#    - role: default_packages
#  tags:
#    - install_packages

#- name: Установка и настройка nginx c кастомной страницей
#  hosts: nginx # Будет работать на узлах в группе nginx
#  roles:
#    - role: nginx_custom
#  tags:
#    - nginx_custom 


- name: Установка postgresql
  hosts: postgres_cluster
  become: yes
  gather_facts: yes
  roles:
    - role: install_postgres
  tags:
    - install_postgres

- name: Установка ssh
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: install_ssh
  tags:
    - install_ssh

- name: Установка ssh
  hosts: postgres_cluster
  become: yes
  gather_facts: yes
  roles:
    - role: install_repmgr
  tags:
    - install_repmgr

