--- 
#- name: Установка стандартных пакетов
#  hosts: all
#  roles:
#    - role: default_packages
#  tags:
#    - install_packages

#- name: Установка и настройка nginx c кастомной страницей
#  hosts: nginx # Будет работать на узлах в группе nginx
#  roles:
#    - role: nginx_custom
#  tags:
#    - nginx_custom 


- name: Установка postgresql, repmgr и запуск кластера
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: postgres_cluster
  tags:
    - postgres_cluster
