# tasks file for nginx_custom

- name: Установка Nginx 
  apt:
    name: "nginx"
    state: present

- name: Подмена веб-страницы
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  when: "'vm_2' in inventory_hostname or 'vm_3' in inventory_hostname" #Выполнится только тогда, когда в имени есть vm_3 или 2
  notify: "Nginx Reloader" 

- name: Настройка прокси
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  when: "'vm_1' in inventory_hostname" #Выполнится только тогда, когда в имени есть vm_1
  notify: "Nginx Reloader" 
